version: '3.8'

services:
  client:
    build:
      context: ./onboarding.client
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - server

  server:
    build:
      context: ./onboarding.server
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
